### ISSUE TITLE
Doesnt work with default Permalink  structure

### ISSUE THREAD

**Issue by towfiqi** [xwp/wp-customize-partial-refresh#14]
When the permalink setting is set to default  and you try to add/edit widgets through customizer, there is an error in console:

`http://localhost/test/test/  - 404 not found. `

My wordpress installation url is http://localhost/test/ but it tries to load http://localhost/test/test/ .

The source of the error is: 
`1. @ customize-partial-refresh-widgets-preview.js   -> LINE: 365 `
`2.  @ customize-partial-refresh-base.js   -> LINE: 92`

But when I set the permalink settings to anything other than the default one, it works fine..

WordPress version: 4.2.3 (The installation is in a subdirectory)
Theme: Twenty Fifteen

**Comment by westonruter** [comment]
Source:
https://wordpress.slack.com/archives/core-customize/p1438440923000658

**Comment by westonruter** [comment]
@towfiqi could you please test if https://github.com/xwp/wp-customize-partial-refresh/pull/15 fixes the issue for you?

**Comment by towfiqi** [comment]
@westonruter It works Great now! Many Thanks.



Another thing I noticed is that plugin doesnt work with php version 5.2. It requires at-least 5.3. Is this possible to make it work on 5.2?

These Are the errors I get in 5.2:

`Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /public_html/wp-content/plugins/customize-partial-refresh/php/class-wp-customize-partial-refresh-plugin.php on line 163`

`Parse error: syntax error, unexpected T_FUNCTION in public_html/wp-content/plugins/customize-partial-refresh/php/class-wp-customize-partial-refresh-widgets.php on line 360`

Thanks

**Comment by westonruter** [comment]
Cheers! I'll address your 5.2 error separately.

**Comment by towfiqi** [comment]
Lovely! It works with php 5.2 now. Many thanks. Your contribution in customizer is really very significant! Hatts off!
